name: dartsideofwebdevelopment
description: A sample web application
dependencies:
  browser: any
  stagexl: any
  stagexl_flump: any
  stagexl_richtextfield: any
  stagexl_spine: any
transformers:
- $dart2js:
    commandLineOptions:
    - --trust-type-annotations
    minify: true